name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0
      - run: trunk build --release --public-url "/${{ github.event.repository.name }}/"
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy:
    name: deploy-gh-pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
